import argparse
vgg_path = '/home/harry/Benchmark/TriTransNet/pretrained/vgg16-397923af.pth'
parser = argparse.ArgumentParser()
parser.add_argument('--n_color', type=int, default=3)
parser.add_argument('--pretrained_model', type=str, default=vgg_path)
parser.add_argument('--num_classes', type=int, default=64)
parser.add_argument('--img_size', type=int, default=32, help='input patch size of network input')
parser.add_argument('--vit_name', type=str, default='ViT-B_16')
parser.add_argument('--vit_patches_size', type=int, default=11, help='vit_patches_size, default is 16')

parser.add_argument('--epoch', type=int, default=150, help='epoch number')
parser.add_argument('--lr', type=float, default=1e-5, help='learning rate')
parser.add_argument('--batchsize', type=int, default=2, help='training batch size')
parser.add_argument('--trainsize', type=int, default=256, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=60, help='every n epochs decay learning rate')
parser.add_argument('--load', type=str, default=None, help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='0', help='train use gpu')
parser.add_argument('--rgb_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TR/RGB/', help='the training rgb images root')
parser.add_argument('--depth_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TR/depth/', help='the training depth images root')
parser.add_argument('--gt_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TR/GT/', help='the training gt images root')
parser.add_argument('--test_rgb_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TE/RGB/', help='the test rgb images root')
parser.add_argument('--test_depth_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TE/depth/', help='the test depth images root')
parser.add_argument('--test_gt_root', type=str, default='/home/harry/Benchmark/VST-main/data/USOD10K/USOD10K_TR/GT/', help='the test gt images root')
parser.add_argument('--save_path', type=str, default='./TriTransNet_cpts/', help='the path to save models and logs')
config = parser.parse_args()
